# Generated by Django 3.1.5 on 2021-10-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('msg', models.SlugField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('msg', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='t',
        ),
        migrations.DeleteModel(
            name='te',
        ),
    ]
