# Generated by Django 3.1.5 on 2021-10-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20211010_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='msg',
            field=models.TextField(max_length=1000),
        ),
    ]
